apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: YOURTOKEN # hcloud project token
---
apiVersion: v1
kind: Secret
metadata:
  name: hrobot
  namespace: kube-system
stringData:
  user: 'YOURROBOTUSER' # robot user
  password: YOURROBOTPASSWORD # robot password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hetzner-cloud-controller-manager
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:hetzner-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hetzner-cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hetzner-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hetzner-cloud-controller-manager
  template:
    metadata:
      labels:
        app: hetzner-cloud-controller-manager
    spec:
      serviceAccountName: hetzner-cloud-controller-manager
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
            - weight: 1
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        # Allow HCCM itself to schedule on nodes that have not yet been initialized by HCCM.
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"

        # Allow HCCM to schedule on control plane nodes.
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
          operator: Exists

        - key: "node.kubernetes.io/not-ready"
          effect: "NoSchedule"
      containers:
        - image: ghcr.io/identw/hetzner-cloud-controller-manager:v0.0.10
          name: hetzner-cloud-controller-manager
          args:
            - "--cloud-provider=hetzner"
            - "--leader-elect=false"
            - "--allow-untagged-cloud"
            - "--route-reconciliation-period=30s"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud
                  key: token
            - name: HROBOT_USER
              valueFrom:
                secretKeyRef:
                  name: hrobot
                  key: user
            - name: HROBOT_PASS
              valueFrom:
                secretKeyRef:
                  name: hrobot
                  key: password
